"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type E={id:string;amountCents:number;arrival?:string|null;message?:string|null;status:string;hauler:{id:string;companyName:string;bio?:string|null;serviceArea?:string|null;vehicleType?:string|null;verified:boolean;rating:number;jobCount:number}};
const money=(c:number)=>"$"+(c/100).toFixed(2);
export default function Estimates({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(""),[es,setEs]=useState<E[]>([]),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 useEffect(()=>{params.then(x=>setId(x.id))},[params]);
 useEffect(()=>{if(!id)return;fetch("/api/jobs/"+id+"/estimates").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load estimates");setEs(d)}).catch(e=>setMsg(e.message))},[id]);
 async function accept(e:E){if(!confirm("Accept this estimate?"))return;setBusy(e.id);setMsg("");try{const r=await fetch("/api/estimates/"+e.id+"/accept",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to accept estimate");setEs(x=>x.map(a=>a.id===e.id?{...a,status:"ACCEPTED"}:{...a,status:a.status==="PENDING"?"DECLINED":a.status}));setMsg(d.message||"Estimate accepted. Continue in the mobile app.")}catch(e){setMsg(e instanceof Error?e.message:"Unable to accept estimate")}finally{setBusy("")}}
 return <main className="container"><header className="nav"><Link href="/dashboard" className="brand"><span className="brandMark">JR</span>JUNK RUN</Link><nav className="navlinks"><Link href="/dashboard">Dashboard</Link><Link href="/jobs">Public jobs</Link></nav></header><section className="section"><div className="eyebrow">Customer estimates</div><h1>Choose a contractor</h1><p className="sub">You can see all estimates for your job. Contractors cannot see competing estimates.</p>{msg&&<div className="card" role="status">{msg}</div>}{!es.length&&!msg&&<div className="card">Loading estimates…</div>}<div className="cards">{es.map(e=><article className="card" key={e.id}><div className="sectionTitle"><h2>{e.hauler.companyName}</h2><span className="pill">{e.status}</span></div><p><strong>{money(e.amountCents)}</strong> estimate</p><p>★ {e.hauler.rating.toFixed(1)} · {e.hauler.jobCount} completed jobs</p><p>{e.hauler.serviceArea||"Service area not listed"}{e.hauler.vehicleType?" · "+e.hauler.vehicleType:""}</p>{e.arrival&&<p><strong>Arrival:</strong> {e.arrival}</p>}{e.message&&<p>{e.message}</p>}<div className="actions"><Link className="btn secondary" href={"/contractors/"+e.hauler.id}>View profile</Link>{e.status==="PENDING"&&<button className="btn primary" disabled={busy===e.id} onClick={()=>accept(e)}>{busy===e.id?"Accepting…":"Accept estimate"}</button>}</div></article>)}</div></section></main>;
}