import Link from "next/link";

const jobs = [
  { id: "JR-1042", category: "Furniture", city: "Phoenix, AZ", desc: "Couch, chairs and miscellaneous household items.", date: "Sep 20" },
  { id: "JR-1041", category: "Yard Waste", city: "Glendale, AZ", desc: "Bagged branches and green waste.", date: "Sep 20" },
  { id: "JR-1039", category: "Appliances", city: "Peoria, AZ", desc: "Appliance removal and general household junk.", date: "Sep 21" }
];

export default function Home() {
  return <>
    <header className="container nav"><Link href="/" className="brand"><span className="brandMark">JR</span>JUNK RUN</Link><nav className="navlinks"><Link href="/jobs">Browse Jobs</Link><Link href="#how">How It Works</Link><Link href="/dashboard">Dashboard</Link><Link href="mailto:BSJInnovations@gmail.com">Contact</Link></nav></header>
    <main>
      <section className="hero"><div className="smoke"/><div className="container heroGrid"><div><div className="eyebrow">Junk removal marketplace</div><h1>CURB IT.<br/><span>WE'LL SERVE IT.</span></h1><p>Junk Run connects customers with independent haulers. Post a load, review estimates, choose a contractor, and let the mobile app handle secure pickup verification and completion.</p><div className="actions"><Link className="btn primary" href="/jobs">Explore Jobs</Link><Link className="btn secondary" href="/dashboard">Open Dashboard</Link></div></div><div className="logoCard"><div className="logoArt"><div><div className="jr"><span className="j">J</span><span className="r">R</span></div><div className="tag">CURB IT. WE'LL SERVE IT.</div></div></div></div></div></section>
      <section className="section" id="how"><div className="container"><div className="eyebrow">One marketplace. Two sides.</div><h2>Built around the app.</h2><p className="sub">The website gives customers and contractors a comfortable place to learn, browse, estimate, communicate and review account activity. Sensitive operational actions remain inside the mobile app.</p><div className="cards"><div className="card"><div className="icon">01</div><h3>Customers</h3><p>Post jobs, receive multiple estimates, accept a contractor, pay online, message, cancel when allowed, and review completed service.</p></div><div className="card"><div className="icon">02</div><h3>Contractors</h3><p>Find available loads, submit estimates, manage awarded work, message customers and review earnings from a desktop.</p></div><div className="card"><div className="icon">03</div><h3>Mobile verification</h3><p>GPS arrival verification, completion photos and closing jobs stay app-only. The website never provides a desktop bypass.</p></div></div></div></section>
      <section className="section alt"><div className="container"><div className="eyebrow">Public jobs</div><h2>See the marketplace without exposing private data.</h2><p className="sub">Public listings show useful job details and city/town only. Names, exact addresses, GPS coordinates, estimates and private information are protected.</p><div className="jobs">{jobs.map(j=><article className="job" key={j.id}><span className="pill">{j.category}</span><h3>{j.id}</h3><p>📍 {j.city}</p><p>📅 Requested pickup: {j.date}</p><p>{j.desc}</p><div className="private">Exact address &amp; contractor estimates are private.</div></article>)}</div><div className="actions"><Link className="btn primary" href="/jobs">View all public jobs</Link></div></div></section>
      <section className="section"><div className="container"><div className="eyebrow">Get the mobile app</div><h2>Do the pickup in the app.</h2><p className="sub">The website is the place to learn and manage marketplace activity. The mobile app remains the required place for GPS arrival verification, completion photos and closing jobs.</p><div className="card" style={{marginTop:30,textAlign:"center"}}><div className="icon">QR</div><h3>App download QR code</h3><p><strong>Launch requirement:</strong> add the final app-download QR code here before publishing.</p></div></div></section><section className="section alt"><div className="container" style={{textAlign:"center"}}><div className="eyebrow">Follow Junk Run</div><h2>Connect with us on Facebook.</h2><div className="card" style={{margin:"30px auto 0",maxWidth:360,textAlign:"center"}}><img src="/facebook-qr.svg" alt="Junk Run Facebook QR code" style={{width:"100%",maxWidth:280,height:"auto",margin:"0 auto"}}/><p style={{marginTop:18}}>Scan to visit the Junk Run Facebook page.</p></div></div></section>
    </main>
    <footer className="footer"><div className="container"><strong>JunkRunApp.com</strong><br/>Independent service providers. Marketplace technology by BSJ Innovation LLC.<br/><a href="mailto:BSJInnovations@gmail.com">BSJInnovations@gmail.com</a><div className="actions"><Link href="/legal/terms">Terms</Link><Link href="/legal/privacy">Privacy</Link><Link href="/legal/contractor">Contractor Agreement</Link><Link href="/legal/customer">Customer Agreement</Link><Link href="/legal/prohibited">Prohibited Items</Link><Link href="/legal/refunds">Refund Policy</Link></div></div></footer>
  </>;
}