"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Job={id:string;jobNumber:string;jobTypes:string;city:string;date:string;time?:string|null;whatToExpect?:string|null;estimates:{id:string;amountCents:number;arrival?:string|null;message?:string|null;status:string}[]};
export default function ContractorJobs(){
 const [jobs,setJobs]=useState<Job[]>([]); const [err,setErr]=useState(""); const [busy,setBusy]=useState<string|null>(null); const [amount,setAmount]=useState<Record<string,string>>({});
 useEffect(()=>{fetch("/api/jobs/available").then(r=>r.json()).then(d=>{if(!Array.isArray(d.jobs))setErr(d.message||d.error||"Unable to load jobs");else setJobs(d.jobs)}).catch(()=>setErr("Unable to load jobs."))},[]);
 async function bid(j:Job){setBusy(j.id);try{const r=await fetch("/api/estimates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:j.id,amountCents:Math.round(Number(amount[j.id])*100),arrival:"Website estimate"})});const d=await r.json();if(!r.ok)throw new Error(typeof d.error==="string"?d.error:"Estimate failed");setJobs(x=>x.map(a=>a.id===j.id?{...a,estimates:[d]}:a))}catch(e){setErr(e instanceof Error?e.message:"Estimate failed")}finally{setBusy(null)}}
 return <main className="container"><header className="nav"><Link href="/" className="brand"><span className="brandMark">JR</span>JUNK RUN</Link><nav className="navlinks"><Link href="/dashboard">Dashboard</Link><Link href="/jobs">Public jobs</Link></nav></header><section className="section"><div className="eyebrow">Contractor marketplace</div><h1>Available loads</h1><p className="sub">Exact addresses and competing estimates stay private.</p>{err&&<div className="card" role="alert">{err}</div>}<div className="jobs">{jobs.map(j=><article className="job" key={j.id}><span className="pill">{j.jobTypes}</span><h3>{j.jobNumber}</h3><p>📍 {j.city} · {j.date}</p><p>{j.whatToExpect||"Junk removal job"}</p>{j.estimates?.length?<div className="private">Your estimate is submitted.</div>:<div className="two"><input type="number" min="0.01" step="0.01" placeholder="Your estimate ($)" value={amount[j.id]||""} onChange={e=>setAmount({...amount,[j.id]:e.target.value})}/><button className="btn primary" disabled={busy===j.id||!amount[j.id]} onClick={()=>bid(j)}>{busy===j.id?"Sending…":"Submit estimate"}</button></div>}</article>)}</div></section></main>
}