"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Load={id:string;jobNumber:string;jobTypes:string;city:string;date:string;whatToExpect?:string|null;estimates:{id:string;amountCents:number;status:string}[]};
type Estimate={id:string;amountCents:number;status:string;job:{jobNumber:string;city:string}};
type Won={id:string;jobNumber:string;status:string;city:string;date:string;priceCents?:number|null};
export default function Dashboard(){
 const [data,setData]=useState<{availableLoads:Load[];submittedEstimates:Estimate[];wonJobs:Won[]}|null>(null),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/contractor/dashboard").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load dashboard");setData(d)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load dashboard"))},[]);
 return <main className="dashboard"><header className="container nav"><Link href="/" className="brand"><span className="brandMark">JR</span>JUNK RUN</Link><nav className="navlinks"><Link href="/contractor/jobs">Available loads</Link><Link href="/jobs">Public jobs</Link></nav></header>
 <section className="container dashHead"><div className="eyebrow">Contractor workspace</div><h1 style={{fontSize:48,margin:"10px 0"}}>Contractor dashboard</h1><p className="sub">Manage available loads, submitted estimates, and jobs awarded to you.</p></section>
 <section className="container">{error&&<div className="card" role="alert">{error}</div>}{!data&&!error&&<div className="card">Loading your dashboard…</div>}{data&&<div className="dashboardSections">
 <section className="card"><div className="sectionTitle"><h2>Available loads</h2><Link href="/contractor/jobs" className="btn secondary">Browse all</Link></div><p className="private">Exact customer addresses remain private until a job is awarded.</p>{data.availableLoads.length===0?<p>No available loads right now.</p>:<div className="jobs">{data.availableLoads.slice(0,10).map(j=><article className="job" key={j.id}><span className="pill">{j.jobTypes}</span><h3>{j.jobNumber}</h3><p>📍 {j.city} · {j.date}</p><p>{j.whatToExpect||"Junk removal job"}</p>{j.estimates.length?<strong>{"Your estimate: $"+(j.estimates[0].amountCents/100).toFixed(2)}</strong>:<Link href="/contractor/jobs" className="btn primary">Submit estimate</Link>}</article>)}</div>}</section>
 <section className="card"><h2>Submitted estimates</h2>{data.submittedEstimates.length===0?<p>You have not submitted any estimates yet.</p>:<div className="table"><div className="row head"><span>Job</span><span>Location</span><span>Estimate</span><span>Status</span></div>{data.submittedEstimates.map(e=><div className="row" key={e.id}><span>{e.job.jobNumber}</span><span>{e.job.city}</span><span>{"$"+(e.amountCents/100).toFixed(2)}</span><span>{e.status}</span></div>)}</div>}</section>
 <section className="card"><h2>Won jobs</h2>{data.wonJobs.length===0?<p>No awarded jobs yet.</p>:<div className="table"><div className="row head"><span>Job</span><span>Status</span><span>Amount</span><span>Date</span></div>{data.wonJobs.map(j=><div className="row" key={j.id}><span>{j.jobNumber}</span><span>{j.status}</span><span>{j.priceCents==null?"—":"$"+(j.priceCents/100).toFixed(2)}</span><span>{j.date}</span></div>)}</div>}<p className="private">Job completion and GPS/photo verification remain available only in the Junk Run mobile app.</p></section>
 </div>}</section></main>;
}