"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Job={id:string;jobNumber:string;status:string;city:string;date:string;time?:string|null;amountCents:number;refundCents:number;paymentStatus:string};
type Totals={earningsCents:number;completedJobs:number;cancelledJobs:number;refundsCents:number;processingFeesCents:number;netEarningsCents:number;processingFeesRecorded:boolean};
type Data={totals:Totals;jobs:Job[];period:string};
const money=(c:number)=>"$"+(c/100).toFixed(2);
export default function Dashboard(){
 const [period,setPeriod]=useState("month"),[data,setData]=useState<Data|null>(null),[error,setError]=useState("");
 useEffect(()=>{setData(null);fetch("/api/contractor/earnings?period="+period).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load earnings");setData(d)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load earnings"))},[period]);
 return <main className="dashboard"><header className="container nav"><Link href="/" className="brand"><span className="brandMark">JR</span>JUNK RUN</Link><nav className="navlinks"><Link href="/contractor/jobs">Available loads</Link><Link href="/jobs">Public jobs</Link></nav></header>
 <section className="container dashHead"><div className="eyebrow">Contractor earnings</div><h1 style={{fontSize:48,margin:"10px 0"}}>Earnings dashboard</h1><p className="sub">Track earnings, completed and cancelled jobs, refunds, processing fees, and job-by-job history.</p><div className="actions"><button className="btn secondary" onClick={()=>setPeriod("week")}>Weekly</button><button className="btn secondary" onClick={()=>setPeriod("month")}>Monthly</button><button className="btn secondary" onClick={()=>setPeriod("year")}>Yearly</button></div></section>
 <section className="container">{error&&<div className="card" role="alert">{error}</div>}{!data&&!error&&<div className="card">Loading earnings…</div>}{data&&<><div className="dashGrid"><div className="metric"><small>Earnings</small><strong>{money(data.totals.earningsCents)}</strong></div><div className="metric"><small>Completed</small><strong>{data.totals.completedJobs}</strong></div><div className="metric"><small>Cancelled</small><strong>{data.totals.cancelledJobs}</strong></div><div className="metric"><small>Refunds</small><strong>{money(data.totals.refundsCents)}</strong></div><div className="metric"><small>Processing fees</small><strong>{data.totals.processingFeesRecorded?money(data.totals.processingFeesCents):"Not recorded"}</strong></div><div className="metric"><small>Net earnings</small><strong>{money(data.totals.netEarningsCents)}</strong></div></div>
 <section className="card"><h2>Job-by-job earnings history</h2>{data.jobs.length===0?<p>No jobs in this period.</p>:<div className="table"><div className="row head"><span>Job</span><span>Status</span><span>Amount</span><span>Date</span></div>{data.jobs.map(j=><div className="row" key={j.id}><span>{j.jobNumber}</span><span>{j.status}</span><span>{money(j.amountCents)}</span><span>{j.date}</span></div>)}</div>}<p className="private">Junk Run platform fees, manually entered expenses, and profit-after-expenses calculations are not included.</p></section>
 </>}</section></main>;
}