"use client";
import {useEffect,useState} from "react"; import Link from "next/link";
type Job={id:string;jobNumber:string;status:string;jobTypes:string;city:string;date:string;time?:string|null;priceCents?:number|null;paymentStatus?:string};
type Session={user:{role:"CUSTOMER"|"HAULER"|"ADMIN"}};
const money=(c:number)=>"$"+((c||0)/100).toFixed(2);
export default function Dashboard(){
 const [role,setRole]=useState<string>(""),[jobs,setJobs]=useState<Job[]>([]),[contractor,setContractor]=useState<any>(null),[earnings,setEarnings]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const s=await fetch("/api/session");const sd=await s.json();if(!s.ok)throw new Error(sd.error||"Please sign in.");const r=sd.user.role;setRole(r);if(r==="CUSTOMER"||r==="ADMIN"){const j=await fetch("/api/jobs/mine");const d=await j.json();if(!j.ok)throw new Error(d.error||"Unable to load jobs");setJobs(d.jobs)}else if(r==="HAULER"){const [d1,d2]=await Promise.all([fetch("/api/contractor/dashboard"),fetch("/api/contractor/earnings?period=month")]);const a=await d1.json(),b=await d2.json();if(!d1.ok)throw new Error(a.error||"Unable to load contractor dashboard");setContractor(a);setEarnings(b)}}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard")}})()},[]);
 return <main className="dashboard"><header className="container nav"><Link href="/" className="brand"><span className="brandMark">JR</span>JUNK RUN</Link><nav className="navlinks"><Link href="/jobs">Public jobs</Link>{role==="HAULER"&&<Link href="/contractor/jobs">Available loads</Link>}<Link href="/legal/terms">Terms</Link></nav></header><section className="container dashHead"><div className="eyebrow">{role||"Account"} dashboard</div><h1>{role==="HAULER"?"Contractor workspace":role==="ADMIN"?"Admin control center":"My Junk Run"}</h1><p className="sub">{role==="HAULER"?"Manage loads, estimates, awarded jobs and earnings. Operational pickup and completion actions remain in the mobile app.":role==="ADMIN"?"Review marketplace users, jobs and audit history.":"Track your jobs, review estimates and manage customer actions."}</p></section><section className="container">{error&&<div className="card" role="alert">{error}</div>}{role==="CUSTOMER"&&<Customer jobs={jobs}/>} {role==="HAULER"&&<Contractor data={contractor} earnings={earnings}/>} {role==="ADMIN"&&<AdminSummary jobs={jobs}/>} {!role&&!error&&<div className="card">Loading dashboard…</div>}</section></main>
}
function Customer({jobs}:{jobs:Job[]}){return <><div className="actions"><Link className="btn primary" href="/customer/jobs/new">Post a job</Link></div><div className="jobs">{jobs.map(j=><article className="job" key={j.id}><span className="pill">{j.status}</span><h3>{j.jobNumber}</h3><p>{j.jobTypes} · 📍 {j.city}</p><p>📅 {j.date}{j.time?" · "+j.time:""}</p>{j.priceCents!=null&&<p><strong>{money(j.priceCents)}</strong></p>}<div className="actions">{["POSTED","BIDDING"].includes(j.status)&&<Link className="btn primary" href={"/customer/jobs/"+j.id+"/estimates"}>View estimates</Link>}<Link className="btn secondary" href={"/jobs/"+j.id}>Public view</Link>{j.status==="AWARDED"&&<Link className="btn secondary" href={"/messages?jobId="+j.id}>Messages</Link>}{!["COMPLETED","CANCELLED"].includes(j.status)&&<Cancel jobId={j.id}/>}</div></article>)}{!jobs.length&&<div className="card"><h3>No jobs yet.</h3><p>Post your first junk-removal job.</p></div>}</div></>}
function Cancel({jobId}:{jobId:string}){const [busy,setBusy]=useState(false);async function go(){const reason=prompt("Why are you cancelling this job?");if(!reason)return;setBusy(true);const r=await fetch("/api/jobs/"+jobId+"/cancel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason})});setBusy(false);if(r.ok)location.reload();else{const d=await r.json();alert(d.error||"Unable to cancel")}}return <button className="btn secondary" onClick={go} disabled={busy}>{busy?"Cancelling…":"Cancel job"}</button>}
function Contractor({data,earnings}:{data:any;earnings:any}){return <><div className="cards"><div className="card"><h3>Available loads</h3><strong className="big">{data?.availableLoads?.length??0}</strong><Link className="btn primary" href="/contractor/jobs">Browse loads</Link></div><div className="card"><h3>Submitted estimates</h3><strong className="big">{data?.submittedEstimates?.length??0}</strong></div><div className="card"><h3>Won jobs</h3><strong className="big">{data?.wonJobs?.length??0}</strong></div></div><div className="card" style={{marginTop:18}}><div className="sectionTitle"><h2>Earnings this month</h2><Link className="btn secondary" href="/dashboard?earnings=1">Earnings dashboard</Link></div><div className="dashGrid"><div className="metric"><small>Earnings</small><strong>{money(earnings?.totals?.earningsCents||0)}</strong></div><div className="metric"><small>Completed</small><strong>{earnings?.totals?.completedJobs||0}</strong></div><div className="metric"><small>Refunds</small><strong>{money(earnings?.totals?.refundsCents||0)}</strong></div><div className="metric"><small>Net</small><strong>{money(earnings?.totals?.netEarningsCents||0)}</strong></div></div></div><div className="actions"><Link className="btn secondary" href="/contractor/profile">Contractor profile</Link></div></>}
function AdminSummary({jobs}:{jobs:Job[]}){return <div className="card"><h2>Admin controls</h2><p>Manage marketplace jobs, users and audit history.</p><Link className="btn primary" href="/admin">Open admin center</Link><h3 style={{marginTop:28}}>Recent jobs</h3>{jobs.slice(0,10).map(j=><p key={j.id}><strong>{j.jobNumber}</strong> · {j.status} · {j.city}</p>)}</div>}
